apiVersion: v1
kind: ServiceAccount
metadata:
  name: chatbot
  namespace: opsera-chatbot-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/opsera-chatbot-dev-role
  labels:
    app: chatbot
    tenant: opsera
