apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-chatbot-dev

resources:
- ../../base

labels:
- pairs:
    environment: dev
  includeSelectors: false

images:
- name: PLACEHOLDER_ECR_URI
  newName: PLACEHOLDER_ECR_URI
  newTag: latest
